export const pcInformation = [
  {
    id: 1,
    brand: "HP",
    model: "Pavilion",
    processor: "Intel Core i5",
    RAM: "8GB",
    storage: "256GB SSD",
    price: 799.99,
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 2,
    brand: "Dell",
    model: "Inspiron",
    processor: "AMD Ryzen 7",
    RAM: "16GB",
    storage: "512GB SSD",
    price: 999.99,
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 3,
    brand: "Apple",
    model: "MacBook Air",
    processor: "Apple M1",
    RAM: "8GB",
    storage: "256GB SSD",
    price: 1099.99,
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 4,
    brand: "Lenovo",
    model: "IdeaPad",
    processor: "Intel Core i7",
    RAM: "12GB",
    storage: "1TB HDD",
    price: 899.99,
    imageUrl: "https://via.placeholder.com/300x200",
  },
  {
    id: 5,
    brand: "Acer",
    model: "Aspire",
    processor: "AMD Ryzen 5",
    RAM: "8GB",
    storage: "512GB SSD",
    price: 749.99,
    imageUrl: "https://via.placeholder.com/300x200",
  },
  // Add more PC information objects as needed
];
